version: '3'
services:
    nginx:
        image: nginx:alpine
        environment:
            TZ: Asia/Taipei
        ports:
            - 80:80
        volumes:
            - ./source:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    php-fpm:
        build: ./php-fpm
        environment:
            TZ: Asia/Taipei
        ports:
            - 9000:9000
        volumes:
            - ./source:/var/www/html    
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 1qaz2wsx3edc
            MYSQL_USER: user
            MYSQL_PASSWORD: 3edc2wsx1qaz
            TZ: Asia/Taipei
        ports:
            - 3306:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/log:/var/log/mysql
            - ./mysql/my.conf:/etc/mysql/my.conf
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - mysql
        environment:
            PMA_HOST: mysql  
        ports:
            - 9100:80
    redis:
        image: redis:latest
        environment:
            TZ: Asia/Taipei
        ports:
            - 6379:6379
        volumes:
            - ./redis/data:/data
            - ./redis/redis.conf:/etc/redis/redis.conf
    phpredisadmin:
        image: erikdubbelboer/phpredisadmin:latest
        links:
            - redis
        environment:
            REDIS_1_HOST: redis
            REDIS_1_PORT: 6379
        ports:
            - 9300:80